sudo: required
dist: trusty

language: haxe

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.2"

install:
  - haxelib install markov-namegen
  - haxelib install nape
  - haxelib install Sure

script:
  - haxe WordReactor.hxml debug.hxml
  - haxe WordReactor.hxml release.hxml